#!/bin/sh

MINGW=/usr/x86_64-w64-mingw32
export PATH=$PATH:$MINGW/bin
#export CFLAGS="-fno-tree-vectorize"
export CXXFLAGS="$CFLAGS"
export CPATH=/usr/x86_64-w64-mingw32/include/qt/QtCore/5.14.0

cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=cmake/modules/Win64Toolchain.cmake -DCMAKE_MODULE_PATH=`pwd`/cmake/modules/ 

make -j5
cpack -G ZIP

