#!/bin/sh

MINGW=/usr/i686-w64-mingw32
export PATH=$PATH:$MINGW/bin
#export CFLAGS="-march=pentium3 -mtune=generic -mpreferred-stack-boundary=5 -fno-tree-vectorize"
export CFLAGS="-march=pentium3 -mtune=generic -mpreferred-stack-boundary=5"
export CXXFLAGS="$CFLAGS"
export CPATH=/usr/i686-w64-mingw32/include/qt/QtCore/5.13.0

cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=cmake/modules/Win32Toolchain.cmake -DCMAKE_MODULE_PATH=`pwd`/cmake/modules/ 

make -j5
cpack -G ZIP
