# this one is important
SET(CMAKE_SYSTEM_NAME Windows)
#this one not so much
SET(CMAKE_SYSTEM_VERSION 1)

# where is the target environment 
SET(CMAKE_FIND_ROOT_PATH	${MINGW_PREFIX})
SET(CMAKE_INSTALL_PREFIX	${MINGW_PREFIX})

SET(MINGW_TOOL_PREFIX		/usr/bin/${CMAKE_SYSTEM_PROCESSOR}-w64-mingw32-)

# specify the cross compiler
SET(CMAKE_C_COMPILER		${MINGW_TOOL_PREFIX}gcc)
SET(CMAKE_CXX_COMPILER		${MINGW_TOOL_PREFIX}g++)
SET(CMAKE_RC_COMPILER		${MINGW_TOOL_PREFIX}gcc)

# specify location of some tools
SET(STRIP					${MINGW_TOOL_PREFIX}strip)
SET(WINDRES					${MINGW_TOOL_PREFIX}windres)
SET(PKG_CONFIG_EXECUTABLE	${MINGW_TOOL_PREFIX}pkg-config)
SET(PKG_CONFIG_FOUND		TRUE)

SET(QT_QMAKE_EXECUTABLE		/usr/bin/${CMAKE_SYSTEM_PROCESSOR}-w64-mingw32-qmake-qt5)
SET(QT_MOC_EXECUTABLE 		/usr/bin/${CMAKE_SYSTEM_PROCESSOR}-w64-mingw32-moc)
SET(QT_RCC_EXECUTABLE		/usr/bin/${CMAKE_SYSTEM_PROCESSOR}-w64-mingw32-rcc)
SET(QT_UIC_EXECUTABLE		/usr/bin/${CMAKE_SYSTEM_PROCESSOR}-w64-mingw32-uic)
# search for programs in the build host directories
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

INCLUDE_DIRECTORIES(${MINGW_PREFIX}/include)
LINK_DIRECTORIES(${MINGW_PREFIX}/lib ${MINGW_PREFIX}/bin)

